name: Build Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (no push)
        run: |
          docker build \
            -f GatewayAPi/Dockerfile \
            -t gatewayapi:${{ github.sha }} \
            .
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and push to Docker Hub
        env:
          IMAGE: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/gatewayapi
        run: |
          docker tag gatewayapi:${{ github.sha }} $IMAGE:${{ github.sha }}
          docker tag gatewayapi:${{ github.sha }} $IMAGE:latest
          docker push $IMAGE:${{ github.sha }}
          docker push $IMAGE:latest

